# Generated by Django 3.2.6 on 2021-08-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
