# Generated by Django 3.2.6 on 2021-08-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestamp',
        ),
    ]
