# Generated by Django 3.2.6 on 2021-08-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_log_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
