# Generated by Django 3.2.6 on 2021-08-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.URLField()),
                ('method', models.CharField(max_length=7)),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
